name: "test-local"

on:
  pull_request:
  push:
    branches:
      - development
      - releases/*

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./read-secret
        name: Read Secret
        id: read-tokens
        with:
          request-tokens: GITHUB_TOKEN
          repository: sheyixx/pipeline-actions
          token:  ${{secrets.GITHUB_TOKEN}}
          ignore-failure: true

      - name: Show results
        env:
          GITHUB_TOKEN: ${{ steps.read-tokens.outputs.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN